import type { AppKitNetwork } from "@reown/appkit-common";
import {
  arbitrum,
  arbitrumSepolia,
  avalanche,
  avalancheFuji,
  base,
  baseSepolia,
  bsc,
  bscTestnet,
  celo,
  celoAlfajores,
  fantom,
  fantomTestnet,
  gnosis,
  linea,
  lineaSepolia,
  mainnet,
  mantle,
  mantleSepoliaTestnet,
  moonbeam,
  moonbaseAlpha,
  optimism,
  optimismSepolia,
  polygon,
  polygonAmoy,
  scroll,
  scrollSepolia,
  sepolia,
  zora,
  zoraSepolia,
} from "@reown/appkit/networks";

export const supportedEvmNetworks: [AppKitNetwork, ...AppKitNetwork[]] = [
  mainnet,
  sepolia,
  arbitrum,
  arbitrumSepolia,
  base,
  baseSepolia,
  optimism,
  optimismSepolia,
  polygon,
  polygonAmoy,
  bsc,
  bscTestnet,
  avalanche,
  avalancheFuji,
  fantom,
  fantomTestnet,
  gnosis,
  celo,
  celoAlfajores,
  moonbeam,
  moonbaseAlpha,
  linea,
  lineaSepolia,
  mantle,
  mantleSepoliaTestnet,
  scroll,
  scrollSepolia,
  zora,
  zoraSepolia,
];

export const defaultNetwork = sepolia;

